# 28-09-2026
# Gadget Sales Dataset
# Comprehensive Filtering & Sorting Question Bank

In [1]:
from pathlib import Path as rasta
import pandas as pd

In [2]:
# Current working directory

Pandas = rasta.cwd()
print(Pandas)

c:\Users\KARTIK JAIN\OneDrive\Desktop\Pandas

In [3]:
print(Pandas/"gadget_sales.csv")

c:\Users\KARTIK JAIN\OneDrive\Desktop\Pandas\gadget_sales.csv

In [4]:
files = sorted(Pandas.glob("*.csv"))
files

# sorted sort karega meta data ke according.
# For example- latest uploaded file will be shown first

print(files)
print(type(files)) # Output ek list aayegi WindowsPath object ki

[WindowsPath('c:/Users/KARTIK JAIN/OneDrive/Desktop/Pandas/employee_data.csv'), WindowsPath('c:/Users/KARTIK JAIN/OneDrive/Desktop/Pandas/employee_performance.csv'), WindowsPath('c:/Users/KARTIK JAIN/OneDrive/Desktop/Pandas/gadget_sales.csv'), WindowsPath('c:/Users/KARTIK JAIN/OneDrive/Desktop/Pandas/high_earners.csv'), WindowsPath('c:/Users/KARTIK JAIN/OneDrive/Desktop/Pandas/logistics_timestamps.csv'), WindowsPath('c:/Users/KARTIK JAIN/OneDrive/Desktop/Pandas/Pokemon.csv')]
<class 'list'>

In [5]:
file_path = files[0]
df_2 = pd.read_csv(file_path)
df = df_2.copy()
df.head(5)

,Employee_ID,Full_Name,Department,Role,Location,Salary,Experience_Years,Project_Code,Email,Is_Active
0,EMP-001,Arjun Verma,Engineering,Senior Developer,Remote - Global,133009,12,PRJ-DELTA,arjun.verma@fastrack.com,True
1,EMP-002,Priya Singh,Data Science,Data Engineer,Remote - India,100409,1,PROJ-GAMMA,priya.singh@analytics.net,True
2,EMP-003,Karan Johar,Marketing,Junior Analyst,Noida HQ,73625,4,PRJ-DELTA,karan.johar@fastrack.com,True
3,EMP-004,Vijay Iyer,HR,Manager,Remote - India,126040,4,PROJ-BETA,vijay.iyer@fastrack.com,True
4,EMP-005,Rohan Das,Engineering,HR Associate,Noida HQ,69089,7,PROJ-BETA,rohan.das@fastrack.com,True

# 1. Basic Filtering & Sorting (Single Condition)

### Q-1 Filter the dataset to show only the transactions where the Unit_Price is greater than $250, and sort the results by Unit_Price from highest to lowest.

In [6]:
import pandas as pd

df = pd.read_csv("gadget_sales.csv")

unit_price = df[df['Unit_Price'] > 250].sort_values(by="Unit_Price", ascending=False)

### Q-2 Extract all rows where the quantity_ordered is 8 or more. sort the ouput chronologically by order_date.

In [7]:

quantity_ordered = df[df["Quantity_Ordered"] >= 8].sort_values(by="Order_Date", ascending=True)
quantity_ordered.head(10)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
1,ORD1001,2024-01-02,Gaming,USB-C MegaDock,8,121.90,Sydney,PayPal,NaN,True,0.05,No Return,WH-5
2,ORD1002,2024-01-03,Smart Home,Smart Thermostat,8,292.69,Berlin,Debit Card,2.0,False,0.05,No Return,WH-4
5,ORD1005,2024-01-06,Wearables,RGB Mechanical Keyboard,10,92.05,Berlin,Crypto,5.0,False,0.00,No Return,WH-5
6,ORD1006,2024-01-07,Smart Home,Smart Eco Hub,9,55.39,Mumbai,Debit Card,5.0,True,0.00,No Return,WH-2
10,ORD1010,2024-01-11,Accessories,USB-C MegaDock,10,257.80,Sydney,PayPal,2.0,False,0.00,No Return,WH-2
12,ORD1012,2024-01-13,Gaming,Wireless Buds Pro,8,120.62,London,Crypto,5.0,False,0.00,No Return,WH-4
15,ORD1015,2024-01-16,Wearables,Wireless Buds Pro,9,121.78,Tokyo,Debit Card,4.0,False,0.00,No Return,WH-5
24,ORD1024,2024-01-25,Audio,Noise-Cancel Headphones,8,192.19,Berlin,Crypto,4.0,True,0.20,No Return,WH-5
26,ORD1026,2024-01-27,Smart Home,RGB Mechanical Keyboard,9,282.59,Mumbai,Crypto,5.0,False,0.00,Pending,WH-3
30,ORD1030,2024-01-31,Smart Home,Wireless Buds Pro,8,149.65,Sydney,Debit Card,3.0,False,0.05,No Return,WH-3

### Q-3 Find all sales records belonging to the  'Smart_home' products_category and sort them by store_location alphabtically

In [8]:

df.loc[df['Product_Category'].str.contains("Smart Home", case = False)
       ].sort_values(by="Store_Location", ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
2,ORD1002,2024-01-03,Smart Home,Smart Thermostat,8,292.69,Berlin,Debit Card,2.0,False,0.05,No Return,WH-4
159,ORD1159,2024-06-08,Smart Home,Noise-Cancel Headphones,4,245.44,Berlin,Crypto,5.0,True,0.05,No Return,WH-1
373,ORD1373,2025-01-08,Smart Home,Smart Thermostat,7,70.96,Berlin,Debit Card,5.0,True,0.05,No Return,WH-2
167,ORD1167,2024-06-16,Smart Home,Noise-Cancel Headphones,3,30.32,Berlin,Debit Card,4.0,False,0.15,No Return,WH-1
424,ORD1424,2025-02-28,Smart Home,Ultra-Wide Monitor,6,221.98,Berlin,PayPal,3.0,False,0.00,Pending,WH-4

### Q-4 Filter for all orders that were paid using the "Crypto" Payment_Method. Sort the results by Customer_Rating in descending order.

In [9]:
df.loc[df['Payment_Method'].str.contains('Crypto', case = False)].sort_values(by="Customer_Rating", ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
5,ORD1005,2024-01-06,Wearables,RGB Mechanical Keyboard,10,92.05,Berlin,Crypto,5.0,False,0.00,No Return,WH-5
12,ORD1012,2024-01-13,Gaming,Wireless Buds Pro,8,120.62,London,Crypto,5.0,False,0.00,No Return,WH-4
52,ORD1052,2024-02-22,Accessories,Smart Eco Hub,6,333.24,London,Crypto,5.0,False,0.00,No Return,WH-5
29,ORD1029,2024-01-30,Accessories,USB-C MegaDock,3,272.01,Berlin,Crypto,5.0,False,0.10,Completed,WH-5
27,ORD1027,2024-01-28,Wearables,RGB Mechanical Keyboard,7,349.31,Mumbai,Crypto,5.0,False,0.05,No Return,WH-5

### Q-5 list all orders where Is_Express-Shipping True. Sort them so that the newest orders appear at the very top

In [10]:
df[df['Is_Express_Shipping'] == True
   ].sort_values(by=['Order_Date'], ascending=False)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
499,ORD1499,2025-05-14,Audio,Ultra-Wide Monitor,4,110.43,Mumbai,Crypto,3.0,True,0.00,Completed,WH-5
496,ORD1496,2025-05-11,Smart Home,Noise-Cancel Headphones,2,48.98,Sydney,Crypto,1.0,True,0.00,No Return,WH-3
492,ORD1492,2025-05-07,Accessories,Smart Eco Hub,7,325.56,Berlin,Debit Card,4.0,True,0.00,No Return,WH-3
490,ORD1490,2025-05-05,Audio,USB-C MegaDock,7,315.84,Mumbai,Debit Card,3.0,True,0.00,No Return,WH-2
489,ORD1489,2025-05-04,Wearables,Wireless Buds Pro,10,231.90,London,Debit Card,4.0,True,0.05,Pending,WH-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,ORD1007,2024-01-08,Smart Home,Smart Eco Hub,5,40.78,London,Debit Card,3.0,True,0.15,Pending,WH-5
6,ORD1006,2024-01-07,Smart Home,Smart Eco Hub,9,55.39,Mumbai,Debit Card,5.0,True,0.00,No Return,WH-2
4,ORD1004,2024-01-05,Gaming,Ultra-Wide Monitor,3,214.75,London,Crypto,3.0,True,0.10,No Return,WH-5
3,ORD1003,2024-01-04,Gaming,Wireless Buds Pro,1,27.40,Tokyo,PayPal,3.0,True,0.00,No Return,WH-4
1,ORD1001,2024-01-02,Gaming,USB-C MegaDock,8,121.90,Sydney,PayPal,NaN,True,0.05,No Return,WH-5

### Q-6 Filter out any orders that didn't recieve a perfect Customer_Rating of 5.0. Sort the remaining list by Order_ID

In [11]:
df[df['Customer_Rating'] != 5.0].sort_values(by='Order_ID', ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
499,ORD1499,2025-05-14,Audio,Ultra-Wide Monitor,4,110.43,Mumbai,Crypto,3.0,True,0.00,Completed,WH-5
498,ORD1498,2025-05-13,Audio,Noise-Cancel Headphones,2,101.02,Sydney,Crypto,1.0,False,0.15,No Return,WH-3
497,ORD1497,2025-05-12,Audio,USB-C MegaDock,7,177.77,Mumbai,Credit Card,4.0,False,0.00,No Return,WH-2
496,ORD1496,2025-05-11,Smart Home,Noise-Cancel Headphones,2,48.98,Sydney,Crypto,1.0,True,0.00,No Return,WH-3
495,ORD1495,2025-05-10,Audio,FitBand X,8,132.79,Sydney,Debit Card,3.0,False,0.00,No Return,WH-5

### Q-7  Retrieve all sales data originating from the "Tokyo" Store_Location. Sort the dataset by the total quantity ordered in ascending order

In [12]:
df[(df['Store_Location'] == 'Tokyo')].sort_values(by='Quantity_Ordered', ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
3,ORD1003,2024-01-04,Gaming,Wireless Buds Pro,1,27.40,Tokyo,PayPal,3.0,True,0.00,No Return,WH-4
59,ORD1059,2024-02-29,Wearables,FitBand X,1,220.49,Tokyo,Debit Card,2.0,False,0.00,No Return,WH-1
95,ORD1095,2024-04-05,Smart Home,Smart Eco Hub,1,303.81,Tokyo,Credit Card,1.0,True,0.15,No Return,WH-5
86,ORD1086,2024-03-27,Audio,Noise-Cancel Headphones,1,194.89,Tokyo,PayPal,2.0,False,0.00,No Return,WH-1
140,ORD1140,2024-05-20,Audio,RGB Mechanical Keyboard,1,185.00,Tokyo,PayPal,4.0,False,0.15,No Return,WH-3

### Que-8 Show all transactions that received a Discount_Percent of 10% or more, sorting them by Unit_Price in ascending order.

In [13]:
df[(df['Discount_Percent'] >= 0.10)
   ].sort_values(by='Unit_Price', ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
256,ORD1256,2024-09-13,Audio,Wireless Buds Pro,1,18.27,New York,Crypto,4.0,False,0.20,Pending,WH-2
237,ORD1237,2024-08-25,Accessories,FitBand X,6,18.89,Berlin,Crypto,5.0,True,0.10,No Return,WH-3
22,ORD1022,2024-01-23,Accessories,Smart Eco Hub,7,22.13,London,Crypto,3.0,False,0.15,No Return,WH-2
175,ORD1175,2024-06-24,Wearables,Ultra-Wide Monitor,8,22.41,Mumbai,Crypto,1.0,False,0.15,No Return,WH-5
20,ORD1020,2024-01-21,Wearables,Smart Thermostat,6,23.17,London,Credit Card,5.0,False,0.20,No Return,WH-4

### Que-9 Filter the dataset to show only orders where the Return_Status is "Pending". Sort the list alphabetically by the Product_Name.

In [14]:
df[df["Return_Status"] == 'Pending'
   ].sort_values(by='Product_Name', ascending=True)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
119,ORD1119,2024-04-29,Wearables,Noise-Cancel Headphones,7,282.14,London,PayPal,4.0,True,0.00,Pending,WH-3
26,ORD1026,2024-01-27,Smart Home,RGB Mechanical Keyboard,9,282.59,Mumbai,Crypto,5.0,False,0.00,Pending,WH-3
7,ORD1007,2024-01-08,Smart Home,Smart Eco Hub,5,40.78,London,Debit Card,3.0,True,0.15,Pending,WH-5
457,ORD1457,2025-04-02,Smart Home,Smart Eco Hub,2,123.74,Berlin,Crypto,3.0,True,0.10,Pending,WH-1
177,ORD1177,2024-06-26,Audio,Smart Thermostat,6,178.70,New York,Credit Card,3.0,True,0.00,Pending,WH-1
180,ORD1180,2024-06-29,Audio,Smart Thermostat,10,164.38,Mumbai,Crypto,4.0,False,0.20,Pending,WH-4
382,ORD1382,2025-01-17,Audio,Smart Thermostat,2,305.87,New York,PayPal,3.0,True,0.00,Pending,WH-3
378,ORD1378,2025-01-13,Wearables,Smart Thermostat,10,174.00,London,PayPal,4.0,True,0.00,Pending,WH-3
152,ORD1152,2024-06-01,Audio,USB-C MegaDock,2,196.32,London,PayPal,5.0,True,0.00,Pending,WH-5
189,ORD1189,2024-07-08,Smart Home,USB-C MegaDock,5,42.60,London,Debit Card,1.0,False,0.00,Pending,WH-3
334,ORD1334,2024-11-30,Accessories,USB-C MegaDock,5,85.57,Mumbai,Debit Card,5.0,True,0.00,Pending,WH-3
65,ORD1065,2024-03-06,Accessories,Ultra-Wide Monitor,1,218.59,New York,Crypto,5.0,True,0.00,Pending,WH-1
424,ORD1424,2025-02-28,Smart Home,Ultra-Wide Monitor,6,221.98,Berlin,PayPal,3.0,False,0.00,Pending,WH-4
229,ORD1229,2024-08-17,Accessories,Ultra-Wide Monitor,10,82.18,Sydney,PayPal,4.0,True,0.10,Pending,WH-3
336,ORD1336,2024-12-02,Audio,Ultra-Wide Monitor,10,226.57,Sydney,Credit Card,4.0,False,0.20,Pending,WH-2
217,ORD1217,2024-08-05,Accessories,Wireless Buds Pro,9,269.94,London,Debit Card,NaN,False,0.10,Pending,WH-4
243,ORD1243,2024-08-31,Smart Home,Wireless Buds Pro,5,247.82,Sydney,Debit Card,5.0,True,0.00,Pending,WH-1
161,ORD1161,2024-06-10,Audio,Wireless Buds Pro,4,115.82,Mumbai,Crypto,4.0,False,0.10,Pending,WH-4
256,ORD1256,2024-09-13,Audio,Wireless Buds Pro,1,18.27,New York,Crypto,4.0,False,0.20,Pending,WH-2
489,ORD1489,2025-05-04,Wearables,Wireless Buds Pro,10,231.90,London,Debit Card,4.0,True,0.05,Pending,WH-2

### Que-10 ind all orders fulfilled by warehouse "WH-5". Sort the output by Order_Date from oldest to newest.

In [15]:

df[df['Warehouse_Code'] == 'WH-5'
   ].sort_values(by='Order_Date', ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
1,ORD1001,2024-01-02,Gaming,USB-C MegaDock,8,121.90,Sydney,PayPal,NaN,True,0.05,No Return,WH-5
4,ORD1004,2024-01-05,Gaming,Ultra-Wide Monitor,3,214.75,London,Crypto,3.0,True,0.10,No Return,WH-5
5,ORD1005,2024-01-06,Wearables,RGB Mechanical Keyboard,10,92.05,Berlin,Crypto,5.0,False,0.00,No Return,WH-5
7,ORD1007,2024-01-08,Smart Home,Smart Eco Hub,5,40.78,London,Debit Card,3.0,True,0.15,Pending,WH-5
13,ORD1013,2024-01-14,Wearables,Smart Eco Hub,6,195.73,New York,Credit Card,4.0,False,0.00,No Return,WH-5

### Que-11 Isolate all transactions where the Discount_Percent is exactly 0.0. Sort them by  Customer_Rating from highest to lowest.

In [16]:
df[df['Discount_Percent'] == 0.0
   ].sort_values(by='Customer_Rating', ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
5,ORD1005,2024-01-06,Wearables,RGB Mechanical Keyboard,10,92.05,Berlin,Crypto,5.0,False,0.0,No Return,WH-5
6,ORD1006,2024-01-07,Smart Home,Smart Eco Hub,9,55.39,Mumbai,Debit Card,5.0,True,0.0,No Return,WH-2
12,ORD1012,2024-01-13,Gaming,Wireless Buds Pro,8,120.62,London,Crypto,5.0,False,0.0,No Return,WH-4
26,ORD1026,2024-01-27,Smart Home,RGB Mechanical Keyboard,9,282.59,Mumbai,Crypto,5.0,False,0.0,Pending,WH-3
11,ORD1011,2024-01-12,Smart Home,RGB Mechanical Keyboard,2,36.89,Berlin,PayPal,5.0,True,0.0,No Return,WH-4

### Q-12 Filter the data exclusively for "Wireless Buds Pro" purchases. Sort the resulting list by Quantity_Ordered in descending order.

In [17]:
df[(df['Product_Name'] == 'Wireless Buds Pro')
   ].sort_values(by='Quantity_Ordered', ascending = False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
479,ORD1479,2025-04-24,Gaming,Wireless Buds Pro,10,209.36,Berlin,Debit Card,5.0,True,0.10,No Return,WH-1
404,ORD1404,2025-02-08,Accessories,Wireless Buds Pro,10,187.72,Tokyo,Debit Card,4.0,True,0.20,No Return,WH-4
153,ORD1153,2024-06-02,Audio,Wireless Buds Pro,10,337.60,Mumbai,PayPal,4.0,True,0.05,No Return,WH-5
69,ORD1069,2024-03-10,Accessories,Wireless Buds Pro,10,88.86,New York,PayPal,4.0,True,0.15,No Return,WH-3
489,ORD1489,2025-05-04,Wearables,Wireless Buds Pro,10,231.90,London,Debit Card,4.0,True,0.05,Pending,WH-2

# 2. Multi-Criteria Filtering (AND / OR Logic)

### Que-1 Filter for orders where the Product_Category is "Audio" and the Unit_Price is above $150. Sort the final list by Unit_Price descending.

In [18]:
df[(df['Product_Category'] == 'Audio') & (df['Unit_Price'] > 150.0)
   ].sort_values(by='Unit_Price', ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
182,ORD1182,2024-07-01,Audio,USB-C MegaDock,8,349.04,London,Crypto,4.0,False,0.00,No Return,WH-3
306,ORD1306,2024-11-02,Audio,Wireless Buds Pro,5,348.77,New York,Debit Card,4.0,True,0.10,No Return,WH-5
250,ORD1250,2024-09-07,Audio,Wireless Buds Pro,5,345.53,Mumbai,Credit Card,4.0,True,0.15,No Return,WH-2
439,ORD1439,2025-03-15,Audio,Noise-Cancel Headphones,2,342.35,New York,Debit Card,4.0,True,0.00,No Return,WH-4
170,ORD1170,2024-06-19,Audio,USB-C MegaDock,4,339.57,New York,PayPal,4.0,False,0.00,No Return,WH-4

### Que-2 Find all orders from the "Berlin" store that either had a discount greater than 0% or utilized express shipping. Sort by Order_Date.

In [19]:

df[(df['Store_Location'] == 'Berlin') &
   ((df['Is_Express_Shipping']) |
    (df['Discount_Percent'] > 0.0))
    ].head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
2,ORD1002,2024-01-03,Smart Home,Smart Thermostat,8,292.69,Berlin,Debit Card,2.0,False,0.05,No Return,WH-4
11,ORD1011,2024-01-12,Smart Home,RGB Mechanical Keyboard,2,36.89,Berlin,PayPal,5.0,True,0.00,No Return,WH-4
16,ORD1016,2024-01-17,Accessories,Noise-Cancel Headphones,1,224.67,Berlin,Credit Card,NaN,True,0.10,No Return,WH-4
23,ORD1023,2024-01-24,Audio,FitBand X,4,308.03,Berlin,Debit Card,1.0,False,0.15,No Return,WH-3
24,ORD1024,2024-01-25,Audio,Noise-Cancel Headphones,8,192.19,Berlin,Crypto,4.0,True,0.20,No Return,WH-5

### Que-3 Filter for products that cost less than $50 and achieved a Customer Rating of 4.5 or higher. Sort by Product_Category alphabetically.

In [20]:

df[(df['Unit_Price'] < 50) &
   (df['Customer_Rating'] >= 4.5)
   ].sort_values(by='Product_Category', ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
132,ORD1132,2024-05-12,Accessories,Ultra-Wide Monitor,6,24.80,Tokyo,Credit Card,5.0,True,0.00,No Return,WH-2
237,ORD1237,2024-08-25,Accessories,FitBand X,6,18.89,Berlin,Crypto,5.0,True,0.10,No Return,WH-3
246,ORD1246,2024-09-03,Accessories,FitBand X,1,28.27,Berlin,Credit Card,5.0,True,0.00,No Return,WH-2
273,ORD1273,2024-09-30,Accessories,Wireless Buds Pro,3,25.58,Berlin,Debit Card,5.0,False,0.00,No Return,WH-4
364,ORD1364,2024-12-30,Accessories,Smart Eco Hub,9,39.62,Mumbai,Crypto,5.0,False,0.05,No Return,WH-4

### Que-4 Select all orders from "Mumbai" or "Sydney" where the Payment_Method

In [21]:
df[(df['Store_Location'].isin(['Mumbai', 'Sydney'])) &
   (df['Payment_Method'] == 'PayPal')
   ].sort_values(by=['Store_Location','Order_Date'], ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
14,ORD1014,2024-01-15,Accessories,USB-C MegaDock,5,279.89,Mumbai,PayPal,NaN,False,0.00,No Return,WH-4
72,ORD1072,2024-03-13,Gaming,FitBand X,10,132.29,Mumbai,PayPal,3.0,True,0.00,No Return,WH-2
79,ORD1079,2024-03-20,Accessories,Smart Thermostat,9,147.74,Mumbai,PayPal,5.0,False,0.00,No Return,WH-1
128,ORD1128,2024-05-08,Gaming,Wireless Buds Pro,8,267.16,Mumbai,PayPal,5.0,False,0.00,No Return,WH-2
153,ORD1153,2024-06-02,Audio,Wireless Buds Pro,10,337.60,Mumbai,PayPal,4.0,True,0.05,No Return,WH-5

### Que-5 Identity orders where the Return_status is "completed" but the Customer_Rating was less than or equal to 2.0. Sort by Customer_Rating ascending.

In [22]:
df[(df['Return_Status'] == 'Completed') &
   (df['Customer_Rating'] <= 2.0)
   ].sort_values(by='Customer_Rating', ascending=True)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
186,ORD1186,2024-07-05,Gaming,FitBand X,8,281.26,New York,Debit Card,1.0,False,0.20,Completed,WH-1
241,ORD1241,2024-08-29,Audio,Smart Eco Hub,4,216.01,London,Credit Card,1.0,True,0.00,Completed,WH-1
359,ORD1359,2024-12-25,Gaming,Ultra-Wide Monitor,3,274.11,Tokyo,Credit Card,1.0,False,0.10,Completed,WH-1
46,ORD1046,2024-02-16,Wearables,Noise-Cancel Headphones,8,20.99,London,Crypto,2.0,False,0.00,Completed,WH-1
200,ORD1200,2024-07-19,Wearables,Wireless Buds Pro,9,106.86,Mumbai,Debit Card,2.0,False,0.00,Completed,WH-2
63,ORD1063,2024-03-04,Wearables,Ultra-Wide Monitor,4,330.82,London,Debit Card,2.0,True,0.00,Completed,WH-4
233,ORD1233,2024-08-21,Accessories,Noise-Cancel Headphones,2,105.11,London,Crypto,2.0,False,0.05,Completed,WH-4
247,ORD1247,2024-09-04,Audio,Wireless Buds Pro,6,175.97,Mumbai,Credit Card,2.0,False,0.00,Completed,WH-4
370,ORD1370,2025-01-05,Wearables,Wireless Buds Pro,10,98.32,Tokyo,Credit Card,2.0,False,0.00,Completed,WH-5
402,ORD1402,2025-02-06,Audio,RGB Mechanical Keyboard,10,305.75,Berlin,PayPal,2.0,False,0.00,Completed,WH-5
491,ORD1491,2025-05-06,Gaming,FitBand X,5,96.57,New York,PayPal,2.0,False,0.10,Completed,WH-1

### Que-6 Filter for orders of "Ultra-wide Monitor" or "RGB Mechanical Keyboard" where the Quantity_Ordered is greather than 5. Sort by Quantity_Ordered descending.

In [23]:
df[(df['Product_Name']).isin(['Ultra-Wide Monitor', 'RGB Mechanical Keyboard']) &
   (df['Quantity_Ordered'] > 5)
   ].sort_values(by='Quantity_Ordered', ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
5,ORD1005,2024-01-06,Wearables,RGB Mechanical Keyboard,10,92.05,Berlin,Crypto,5.0,False,0.0,No Return,WH-5
224,ORD1224,2024-08-12,Audio,RGB Mechanical Keyboard,10,176.31,Mumbai,Credit Card,4.0,True,0.0,No Return,WH-3
229,ORD1229,2024-08-17,Accessories,Ultra-Wide Monitor,10,82.18,Sydney,PayPal,4.0,True,0.1,Pending,WH-3
206,ORD1206,2024-07-25,Gaming,RGB Mechanical Keyboard,10,25.43,Mumbai,PayPal,NaN,False,0.0,No Return,WH-1
51,ORD1051,2024-02-21,Accessories,RGB Mechanical Keyboard,10,88.12,Berlin,Credit Card,5.0,False,0.0,No Return,WH-3

### Que-7 New York Electronic Clearance: Find all rows where the location is "New York", the category is "Gaming", and a discount was applied. Sort by Discount_Percent descending.

In [24]:
df[(df['Store_Location'] == 'New York') &
   (df['Product_Category'] == 'Gaming') &
   (df['Discount_Percent'] > 0.0)
   ].sort_values(by='Discount_Percent', ascending=False)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
186,ORD1186,2024-07-05,Gaming,FitBand X,8,281.26,New York,Debit Card,1.0,False,0.20,Completed,WH-1
384,ORD1384,2025-01-19,Gaming,Smart Eco Hub,5,52.49,New York,PayPal,5.0,False,0.15,No Return,WH-1
309,ORD1309,2024-11-05,Gaming,Noise-Cancel Headphones,1,81.85,New York,Crypto,1.0,False,0.10,No Return,WH-4
71,ORD1071,2024-03-12,Gaming,Smart Eco Hub,7,276.16,New York,Credit Card,4.0,False,0.10,No Return,WH-5
62,ORD1062,2024-03-03,Gaming,RGB Mechanical Keyboard,5,92.61,New York,Credit Card,5.0,False,0.10,No Return,WH-5
491,ORD1491,2025-05-06,Gaming,FitBand X,5,96.57,New York,PayPal,2.0,False,0.10,Completed,WH-1
357,ORD1357,2024-12-23,Gaming,RGB Mechanical Keyboard,1,235.01,New York,Credit Card,3.0,False,0.10,No Return,WH-3
47,ORD1047,2024-02-17,Gaming,FitBand X,10,345.89,New York,Debit Card,3.0,False,0.05,No Return,WH-5
444,ORD1444,2025-03-20,Gaming,FitBand X,1,262.38,New York,Crypto,5.0,True,0.05,No Return,WH-4

### Que-8 Extract records from "WH-1" or "WH-4" where the quantity ordered is exactly 10. Sort by Warehouse_Code and then by Order_ID.

In [25]:
df[(df["Warehouse_Code"].isin(['WH-1','WH-4'])) &
   (df['Quantity_Ordered'] == 10)
   ].sort_values(by=['Warehouse_Code', 'Order_Date'], ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
155,ORD1155,2024-06-04,Audio,Noise-Cancel Headphones,10,226.93,New York,Crypto,4.0,False,0.00,No Return,WH-1
174,ORD1174,2024-06-23,Accessories,Smart Thermostat,10,23.24,Mumbai,Debit Card,4.0,False,0.15,Completed,WH-1
181,ORD1181,2024-06-30,Smart Home,FitBand X,10,106.66,Berlin,Credit Card,3.0,False,0.00,No Return,WH-1
193,ORD1193,2024-07-12,Wearables,USB-C MegaDock,10,333.54,Tokyo,Credit Card,4.0,False,0.20,No Return,WH-1
195,ORD1195,2024-07-14,Smart Home,Smart Eco Hub,10,159.83,New York,PayPal,3.0,False,0.00,No Return,WH-1

### Que-9 Filter for "Debit Card" transactions that occured in "London" with a customer rating strictly above 3.0 sort Chronologically

In [26]:
df[(df['Payment_Method'] == 'Debit Card') &
   (df['Store_Location'] == 'London') &
   (df['Customer_Rating'] > 3.0)
   ].sort_values(by='Customer_Rating', ascending= True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
56,ORD1056,2024-02-26,Accessories,USB-C MegaDock,1,309.50,London,Debit Card,4.0,False,0.00,No Return,WH-5
85,ORD1085,2024-03-26,Audio,Wireless Buds Pro,3,89.98,London,Debit Card,4.0,False,0.00,No Return,WH-3
290,ORD1290,2024-10-17,Smart Home,FitBand X,2,260.08,London,Debit Card,4.0,False,0.00,No Return,WH-4
333,ORD1333,2024-11-29,Gaming,FitBand X,1,320.64,London,Debit Card,4.0,False,0.05,No Return,WH-5
469,ORD1469,2025-04-14,Accessories,Smart Eco Hub,5,222.53,London,Debit Card,4.0,True,0.00,No Return,WH-3

### Que-10 Find all express shipping orders that have a Customer_rating of 2.0 or lower (or are missing a rating). Sort by Customer_rating ascending.

In [27]:
df[ (df['Is_Express_Shipping']) &
   (df['Customer_Rating'] <= 2.0) |
   (df['Customer_Rating'].isna())
   ].sort_values(by='Customer_Rating', ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
74,ORD1074,2024-03-15,Gaming,RGB Mechanical Keyboard,8,339.65,Tokyo,Debit Card,1.0,True,0.00,No Return,WH-4
95,ORD1095,2024-04-05,Smart Home,Smart Eco Hub,1,303.81,Tokyo,Credit Card,1.0,True,0.15,No Return,WH-5
104,ORD1104,2024-04-14,Audio,Noise-Cancel Headphones,5,181.12,Mumbai,Crypto,1.0,True,0.00,No Return,WH-5
116,ORD1116,2024-04-26,Wearables,RGB Mechanical Keyboard,3,204.52,Sydney,Debit Card,1.0,True,0.00,No Return,WH-2
133,ORD1133,2024-05-13,Gaming,RGB Mechanical Keyboard,6,291.65,Mumbai,Credit Card,1.0,True,0.00,No Return,WH-3

### Que-11 Isolate "Waerables" category orders that placed at "WH-2" with a unit price between $100 and $200. Sort by unit_price.

In [28]:
df[(df['Product_Category'] == 'Wearables') &\
    (df['Warehouse_Code'] == 'WH-2') &\
          (df['Unit_Price'].between(100, 200, inclusive='both'))
          ].sort_values(by='Unit_Price', ascending=True).head(10)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
200,ORD1200,2024-07-19,Wearables,Wireless Buds Pro,9,106.86,Mumbai,Debit Card,2.0,False,0.00,Completed,WH-2
320,ORD1320,2024-11-16,Wearables,Ultra-Wide Monitor,7,139.30,Berlin,PayPal,3.0,False,0.15,No Return,WH-2
350,ORD1350,2024-12-16,Wearables,Smart Thermostat,10,187.46,Sydney,Credit Card,4.0,True,0.10,Completed,WH-2
148,ORD1148,2024-05-28,Wearables,RGB Mechanical Keyboard,7,195.90,Sydney,Debit Card,4.0,False,0.10,No Return,WH-2

### Que-12 Filter for orders paid via "Crypto" that have a return_status of "No_return". Sort by Quantity_ordered from highest to lowest.

In [29]:
df[(df['Payment_Method'] == 'Crypto') &\
    (df['Return_Status'] == 'No Return')
    ].sort_values(by='Quantity_Ordered', ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
5,ORD1005,2024-01-06,Wearables,RGB Mechanical Keyboard,10,92.05,Berlin,Crypto,5.0,False,0.0,No Return,WH-5
155,ORD1155,2024-06-04,Audio,Noise-Cancel Headphones,10,226.93,New York,Crypto,4.0,False,0.0,No Return,WH-1
287,ORD1287,2024-10-14,Gaming,Noise-Cancel Headphones,10,166.53,London,Crypto,3.0,False,0.2,No Return,WH-5
482,ORD1482,2025-04-27,Wearables,FitBand X,10,271.24,Sydney,Crypto,5.0,False,0.2,No Return,WH-5
323,ORD1323,2024-11-19,Audio,FitBand X,10,305.46,Tokyo,Crypto,5.0,False,0.2,No Return,WH-5

# 3. Advance Sorting & Multi-Level Order

### Que-1 Sort the entire data set primarily by product_category in alphabatically order, and secondary by unit_rice in descending order.

In [30]:
df.sort_values(by=['Product_Category','Unit_Price'
                   ], ascending= [True,False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
77,ORD1077,2024-03-18,Accessories,Ultra-Wide Monitor,1,348.29,London,Crypto,5.0,True,0.05,No Return,WH-2
61,ORD1061,2024-03-02,Accessories,Wireless Buds Pro,6,347.04,London,Crypto,3.0,True,0.00,No Return,WH-5
144,ORD1144,2024-05-24,Accessories,Ultra-Wide Monitor,6,343.70,Mumbai,Debit Card,5.0,True,0.05,No Return,WH-5
307,ORD1307,2024-11-03,Accessories,Wireless Buds Pro,3,341.56,Berlin,PayPal,NaN,False,0.05,No Return,WH-3
169,ORD1169,2024-06-18,Accessories,Smart Eco Hub,4,341.12,New York,PayPal,4.0,True,0.00,No Return,WH-2

### Que-2 sort the data first by store_location (AtoZ) and then by Order_date from oldest to newest.

In [31]:
df.sort_values(by=['Store_Location', 'Order_Date'
                   ], ascending=[True,True]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
2,ORD1002,2024-01-03,Smart Home,Smart Thermostat,8,292.69,Berlin,Debit Card,2.0,False,0.05,No Return,WH-4
5,ORD1005,2024-01-06,Wearables,RGB Mechanical Keyboard,10,92.05,Berlin,Crypto,5.0,False,0.00,No Return,WH-5
11,ORD1011,2024-01-12,Smart Home,RGB Mechanical Keyboard,2,36.89,Berlin,PayPal,5.0,True,0.00,No Return,WH-4
16,ORD1016,2024-01-17,Accessories,Noise-Cancel Headphones,1,224.67,Berlin,Credit Card,NaN,True,0.10,No Return,WH-4
23,ORD1023,2024-01-24,Audio,FitBand X,4,308.03,Berlin,Debit Card,1.0,False,0.15,No Return,WH-3

### Que-3 Filter for "Gaming" items, then sort the results by Quantity Ordered descending, and if quantities are equal, sort by Customer Rating descending.

In [32]:
df[(df['Product_Category'] == 'Gaming')
   ].sort_values(by=['Quantity_Ordered', 'Customer_Rating'], ascending=[False,False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
412,ORD1412,2025-02-16,Gaming,Ultra-Wide Monitor,10,240.60,New York,Debit Card,5.0,True,0.00,No Return,WH-2
479,ORD1479,2025-04-24,Gaming,Wireless Buds Pro,10,209.36,Berlin,Debit Card,5.0,True,0.10,No Return,WH-1
462,ORD1462,2025-04-07,Gaming,Noise-Cancel Headphones,10,165.31,Sydney,PayPal,4.0,False,0.00,No Return,WH-4
47,ORD1047,2024-02-17,Gaming,FitBand X,10,345.89,New York,Debit Card,3.0,False,0.05,No Return,WH-5
72,ORD1072,2024-03-13,Gaming,FitBand X,10,132.29,Mumbai,PayPal,3.0,True,0.00,No Return,WH-2

### Que-4 Sort all discounted items by Discount Percent from highest to lowest, and break tes using Customer_Rating from highest to lowest

In [33]:
df.sort_values(by=['Discount_Percent','Customer_Rating'
                   ], ascending=[False,False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
20,ORD1020,2024-01-21,Wearables,Smart Thermostat,6,23.17,London,Credit Card,5.0,False,0.2,No Return,WH-4
83,ORD1083,2024-03-24,Gaming,Ultra-Wide Monitor,6,288.30,Mumbai,Credit Card,5.0,False,0.2,No Return,WH-4
84,ORD1084,2024-03-25,Audio,USB-C MegaDock,7,90.19,New York,Debit Card,5.0,True,0.2,No Return,WH-5
286,ORD1286,2024-10-13,Accessories,USB-C MegaDock,3,288.79,Tokyo,Crypto,5.0,True,0.2,No Return,WH-4
323,ORD1323,2024-11-19,Audio,FitBand X,10,305.46,Tokyo,Crypto,5.0,False,0.2,No Return,WH-5

### Que-5 Warehouse Logistical Flow: Filter for orders with a "Completed" or "Pending" retum status. Sort the output by Warehouse Code (A to Z) and then by Order Date (Newest to Oldest).

In [34]:
df[df['Return_Status'].isin(["Completed","Pending"])
   ].sort_values(by=['Warehouse_Code', 'Order_Date'], ascending=[True, False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
491,ORD1491,2025-05-06,Gaming,FitBand X,5,96.57,New York,PayPal,2.0,False,0.1,Completed,WH-1
488,ORD1488,2025-05-03,Accessories,USB-C MegaDock,6,17.53,Tokyo,PayPal,3.0,False,0.0,Completed,WH-1
457,ORD1457,2025-04-02,Smart Home,Smart Eco Hub,2,123.74,Berlin,Crypto,3.0,True,0.1,Pending,WH-1
449,ORD1449,2025-03-25,Wearables,FitBand X,9,285.63,New York,Crypto,3.0,True,0.0,Completed,WH-1
359,ORD1359,2024-12-25,Gaming,Ultra-Wide Monitor,3,274.11,Tokyo,Credit Card,1.0,False,0.1,Completed,WH-1

### Que-6 Low Rating Priority Check: Filter for orders with ratings under 3.0. Sort them by Customer Rating ascending, and then by Unit Price descending to see if expensive items are failing expectations.

In [35]:
df[(df['Customer_Rating'] < 3.0)
   ].sort_values(by=['Customer_Rating','Unit_Price'], ascending=[True,False
                                                                 ]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
74,ORD1074,2024-03-15,Gaming,RGB Mechanical Keyboard,8,339.65,Tokyo,Debit Card,1.0,True,0.00,No Return,WH-4
23,ORD1023,2024-01-24,Audio,FitBand X,4,308.03,Berlin,Debit Card,1.0,False,0.15,No Return,WH-3
425,ORD1425,2025-03-01,Wearables,Smart Eco Hub,6,306.08,Tokyo,Debit Card,1.0,True,0.00,No Return,WH-3
95,ORD1095,2024-04-05,Smart Home,Smart Eco Hub,1,303.81,Tokyo,Credit Card,1.0,True,0.15,No Return,WH-5
420,ORD1420,2025-02-24,Wearables,Wireless Buds Pro,6,295.77,London,Debit Card,1.0,False,0.20,No Return,WH-2

### Que-7 Sort the dataset by Payment Method alphabetically, and then by Store Location alphabetically to cluster regional payment types.

In [36]:
df.sort_values(by=['Payment_Method', 'Store_Location'], ascending=[True,True]
               ).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
16,ORD1016,2024-01-17,Accessories,Noise-Cancel Headphones,1,224.67,Berlin,Credit Card,NaN,True,0.1,No Return,WH-4
51,ORD1051,2024-02-21,Accessories,RGB Mechanical Keyboard,10,88.12,Berlin,Credit Card,5.0,False,0.0,No Return,WH-3
60,ORD1060,2024-03-01,Wearables,USB-C MegaDock,10,70.96,Berlin,Credit Card,5.0,False,0.1,Completed,WH-2
108,ORD1108,2024-04-18,Smart Home,RGB Mechanical Keyboard,9,40.50,Berlin,Credit Card,5.0,False,0.0,No Return,WH-4
120,ORD1120,2024-04-30,Wearables,Wireless Buds Pro,1,235.58,Berlin,Credit Card,3.0,True,0.0,No Return,WH-5

### Que-8 Filter for express shipping orders. Sort them first by Quantity_Ordered descending coondiarderly by order_ID ascending

In [37]:
df[(df['Is_Express_Shipping'])
   ].sort_values(by=['Quantity_Ordered','Order_ID'], ascending=[False,True]
                 ).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
69,ORD1069,2024-03-10,Accessories,Wireless Buds Pro,10,88.86,New York,PayPal,4.0,True,0.15,No Return,WH-3
72,ORD1072,2024-03-13,Gaming,FitBand X,10,132.29,Mumbai,PayPal,3.0,True,0.00,No Return,WH-2
106,ORD1106,2024-04-16,Smart Home,Smart Eco Hub,10,88.76,Sydney,Debit Card,5.0,True,0.00,No Return,WH-4
153,ORD1153,2024-06-02,Audio,Wireless Buds Pro,10,337.60,Mumbai,PayPal,4.0,True,0.05,No Return,WH-5
171,ORD1171,2024-06-20,Audio,FitBand X,10,266.13,Mumbai,Credit Card,2.0,True,0.10,No Return,WH-3

# 4. Data-based Filetring and sorting

### Que-1 Filter for all orders placed between january 1, 2024 and March 31, 2024. Sort them chronologically from oldest to newest

In [38]:
# Que-1 Filter for all orders placed between january 1, 2024 and March 31, 2024. Sort them chronologically from oldest to newest

df[(df['Order_Date'] >= '2024-01-01') & (df['Order_Date'] <= '2024-03-31')
   ].sort_values('Order_Date').head(10)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
0,ORD1000,2024-01-01,Accessories,Ultra-Wide Monitor,2,297.92,Tokyo,Debit Card,3.0,False,0.05,No Return,WH-4
1,ORD1001,2024-01-02,Gaming,USB-C MegaDock,8,121.90,Sydney,PayPal,NaN,True,0.05,No Return,WH-5
2,ORD1002,2024-01-03,Smart Home,Smart Thermostat,8,292.69,Berlin,Debit Card,2.0,False,0.05,No Return,WH-4
3,ORD1003,2024-01-04,Gaming,Wireless Buds Pro,1,27.40,Tokyo,PayPal,3.0,True,0.00,No Return,WH-4
4,ORD1004,2024-01-05,Gaming,Ultra-Wide Monitor,3,214.75,London,Crypto,3.0,True,0.10,No Return,WH-5
5,ORD1005,2024-01-06,Wearables,RGB Mechanical Keyboard,10,92.05,Berlin,Crypto,5.0,False,0.00,No Return,WH-5
6,ORD1006,2024-01-07,Smart Home,Smart Eco Hub,9,55.39,Mumbai,Debit Card,5.0,True,0.00,No Return,WH-2
7,ORD1007,2024-01-08,Smart Home,Smart Eco Hub,5,40.78,London,Debit Card,3.0,True,0.15,Pending,WH-5
8,ORD1008,2024-01-09,Smart Home,Wireless Buds Pro,6,248.26,London,Crypto,4.0,True,0.10,No Return,WH-2
9,ORD1009,2024-01-10,Gaming,USB-C MegaDock,4,128.86,New York,Debit Card,4.0,True,0.00,No Return,WH-2

### Que-2 Find for all orders from june or july of any year in the dataset. Sort the results by product_category and then by order_date descending.

In [39]:
# Que-2 Find for all orders from june or july of any year in the dataset. Sort the results by product_category and then by order_date descending.

df["Order_Date"]=pd.to_datetime(df["Order_Date"])

df[df['Order_Date'].dt.month.isin([6, 7])
   ].sort_values(by=['Product_Category', 'Order_Date'],ascending=[True, False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
211,ORD1211,2024-07-30,Accessories,Ultra-Wide Monitor,1,339.34,Berlin,Crypto,4.0,True,0.1,No Return,WH-2
209,ORD1209,2024-07-28,Accessories,Smart Eco Hub,7,304.56,Berlin,Debit Card,4.0,True,0.0,No Return,WH-5
208,ORD1208,2024-07-27,Accessories,Ultra-Wide Monitor,6,138.46,Mumbai,PayPal,3.0,False,0.0,No Return,WH-4
204,ORD1204,2024-07-23,Accessories,USB-C MegaDock,5,92.03,Mumbai,Crypto,4.0,False,0.1,No Return,WH-3
199,ORD1199,2024-07-18,Accessories,Wireless Buds Pro,8,148.19,Berlin,PayPal,4.0,True,0.0,No Return,WH-2

### Que-3 Extract all transactions that occuered in the month od december. Sort thre list by quntity_ordered from highest to lowest

In [40]:
df[df['Order_Date'].dt.month.isin([12])
   ].sort_values(by=['Quantity_Ordered'],ascending=[False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
336,ORD1336,2024-12-02,Audio,Ultra-Wide Monitor,10,226.57,Sydney,Credit Card,4.0,False,0.20,Pending,WH-2
354,ORD1354,2024-12-20,Wearables,USB-C MegaDock,10,146.01,Berlin,Credit Card,4.0,True,0.05,Completed,WH-4
350,ORD1350,2024-12-16,Wearables,Smart Thermostat,10,187.46,Sydney,Credit Card,4.0,True,0.10,Completed,WH-2
361,ORD1361,2024-12-27,Accessories,FitBand X,9,339.89,Berlin,Crypto,4.0,False,0.00,No Return,WH-4
364,ORD1364,2024-12-30,Accessories,Smart Eco Hub,9,39.62,Mumbai,Crypto,5.0,False,0.05,No Return,WH-4

### Que-4 Filter to "Smart Home" orders placed strictly with in the calender 2025. Sort by Unit_Price decending.

In [41]:
df[(df['Product_Category'] == "Smart Home") & (df['Order_Date'].dt.year == 2025)
   ].sort_values(by=['Unit_Price'], ascending=[False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
437,ORD1437,2025-03-13,Smart Home,USB-C MegaDock,9,349.80,Berlin,Credit Card,4.0,False,0.00,No Return,WH-3
397,ORD1397,2025-02-01,Smart Home,FitBand X,9,345.52,London,Debit Card,2.0,False,0.05,No Return,WH-4
485,ORD1485,2025-04-30,Smart Home,Wireless Buds Pro,7,335.10,Mumbai,PayPal,4.0,False,0.05,No Return,WH-4
400,ORD1400,2025-02-04,Smart Home,RGB Mechanical Keyboard,10,333.86,New York,Credit Card,5.0,False,0.15,No Return,WH-2
442,ORD1442,2025-03-18,Smart Home,Ultra-Wide Monitor,9,277.10,London,PayPal,3.0,True,0.15,No Return,WH-4

### Que-5 Filter for all orders placed exactly on "2025-05-01". Sort them alphabetically by store_location.

In [42]:
# df[(df['Order_Date'].dt == '2025-05-01')].sort_values(by=['Store_Location'], ascending=[True]).head()

df[(df['Order_Date'] == '2025-05-01')
   ].sort_values(by=['Store_Location'], ascending=[True]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code
486,ORD1486,2025-05-01,Audio,Wireless Buds Pro,10,21.11,New York,Debit Card,2.0,True,0.0,No Return,WH-1

### Que-6 Filter for orders with a "Pending" return status that were ordered after June 1, 2025. Sort them so the most recent orders appear first.

In [43]:
df[(df['Return_Status'] == 'Pending') &
   (df['Order_Date'] > '2025-06-01')
   ].sort_values(by=['Order_Date'], ascending=False)

Empty DataFrame
Columns: [Order_ID, Order_Date, Product_Category, Product_Name, Quantity_Ordered, Unit_Price, Store_Location, Payment_Method, Customer_Rating, Is_Express_Shipping, Discount_Percent, Return_Status, Warehouse_Code]
Index: []

# 5. Calculated & Conditional string Filtering

### Que-1 Filter for transactions where the calculated total order value (Quantity_Ordered × Unit_Price) exceeds $1,000. Sort by this calculated value descending.

In [44]:
df['Revenue'] = df['Quantity_Ordered'] * df['Unit_Price']

df[(df['Revenue'] > 1000)
   ].sort_values(by=['Revenue'], ascending=[False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
47,ORD1047,2024-02-17,Gaming,FitBand X,10,345.89,New York,Debit Card,3.0,False,0.05,No Return,WH-5,3458.9
153,ORD1153,2024-06-02,Audio,Wireless Buds Pro,10,337.60,Mumbai,PayPal,4.0,True,0.05,No Return,WH-5,3376.0
400,ORD1400,2025-02-04,Smart Home,RGB Mechanical Keyboard,10,333.86,New York,Credit Card,5.0,False,0.15,No Return,WH-2,3338.6
193,ORD1193,2024-07-12,Wearables,USB-C MegaDock,10,333.54,Tokyo,Credit Card,4.0,False,0.20,No Return,WH-1,3335.4
437,ORD1437,2025-03-13,Smart Home,USB-C MegaDock,9,349.80,Berlin,Credit Card,4.0,False,0.00,No Return,WH-3,3148.2

### Que-2 Use string filtering to find all rows where the Product_Name contains the word "Pro". Sort the results alphabetically by store location.

In [45]:
# df[(df['Product_Name'].isin(['pro']))].sort_values(by=['Store_Location'], ascending=[True]).head()

df[df['Product_Name'].str.contains("Pro", case=False)
   ].sort_values(by=['Store_Location'], ascending=[True]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
270,ORD1270,2024-09-27,Smart Home,Wireless Buds Pro,3,50.03,Berlin,Debit Card,4.0,False,0.00,No Return,WH-3,150.09
406,ORD1406,2025-02-10,Audio,Wireless Buds Pro,6,238.40,Berlin,Debit Card,4.0,False,0.15,No Return,WH-2,1430.40
199,ORD1199,2024-07-18,Accessories,Wireless Buds Pro,8,148.19,Berlin,PayPal,4.0,True,0.00,No Return,WH-2,1185.52
418,ORD1418,2025-02-22,Gaming,Wireless Buds Pro,8,74.35,Berlin,Crypto,3.0,False,0.20,No Return,WH-3,594.80
168,ORD1168,2024-06-17,Audio,Wireless Buds Pro,3,306.96,Berlin,PayPal,5.0,True,0.15,No Return,WH-5,920.88

### Que-3 Filter for orders where the Product_Name ends with the word "Keyboard" or "Monitor". Sort the output by Unit_Price ascending.

In [46]:
df[df['Product_Name'].str.lower().str.contains("keyboard|monitor", case=False)
   ].sort_values(by=['Unit_Price'], ascending=[True])

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
175,ORD1175,2024-06-24,Wearables,Ultra-Wide Monitor,8,22.41,Mumbai,Crypto,1.0,False,0.15,No Return,WH-5,179.28
132,ORD1132,2024-05-12,Accessories,Ultra-Wide Monitor,6,24.80,Tokyo,Credit Card,5.0,True,0.00,No Return,WH-2,148.80
206,ORD1206,2024-07-25,Gaming,RGB Mechanical Keyboard,10,25.43,Mumbai,PayPal,NaN,False,0.00,No Return,WH-1,254.30
395,ORD1395,2025-01-30,Gaming,RGB Mechanical Keyboard,8,28.93,Berlin,PayPal,NaN,False,0.00,No Return,WH-5,231.44
45,ORD1045,2024-02-15,Audio,Ultra-Wide Monitor,2,29.10,Sydney,PayPal,5.0,True,0.00,No Return,WH-3,58.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,ORD1074,2024-03-15,Gaming,RGB Mechanical Keyboard,8,339.65,Tokyo,Debit Card,1.0,True,0.00,No Return,WH-4,2717.20
144,ORD1144,2024-05-24,Accessories,Ultra-Wide Monitor,6,343.70,Mumbai,Debit Card,5.0,True,0.05,No Return,WH-5,2062.20
201,ORD1201,2024-07-20,Smart Home,RGB Mechanical Keyboard,6,344.63,London,Debit Card,3.0,False,0.00,Completed,WH-1,2067.78
77,ORD1077,2024-03-18,Accessories,Ultra-Wide Monitor,1,348.29,London,Crypto,5.0,True,0.05,No Return,WH-2,348.29
27,ORD1027,2024-01-28,Wearables,RGB Mechanical Keyboard,7,349.31,Mumbai,Crypto,5.0,False,0.05,No Return,WH-5,2445.17

### Que-4 Filter the dataset to find rows where the Customer_Rating column is null/blank. Sort these missing entries by Order_Date chronologically.

In [47]:
### Que-4 Filter the dataset to find rows where the Customer_Rating column is null/blank. Sort these missing entries by Order_Date chronologically.

df[(df['Customer_Rating'].isna())
               ].sort_values(by=['Order_Date'], ascending = [True]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
1,ORD1001,2024-01-02,Gaming,USB-C MegaDock,8,121.90,Sydney,PayPal,NaN,True,0.05,No Return,WH-5,975.20
14,ORD1014,2024-01-15,Accessories,USB-C MegaDock,5,279.89,Mumbai,PayPal,NaN,False,0.00,No Return,WH-4,1399.45
16,ORD1016,2024-01-17,Accessories,Noise-Cancel Headphones,1,224.67,Berlin,Credit Card,NaN,True,0.10,No Return,WH-4,224.67
57,ORD1057,2024-02-27,Wearables,Wireless Buds Pro,4,331.49,New York,Debit Card,NaN,True,0.00,No Return,WH-1,1325.96
92,ORD1092,2024-04-02,Smart Home,Ultra-Wide Monitor,2,58.39,Sydney,Credit Card,NaN,False,0.05,No Return,WH-4,116.78

### Que-5 Find orders where the quantity_ordered is less than 3 but the Discount_Percent is maximum (10% or higher). Sort by Cusotmer_Rating descending.

In [48]:
df[(df['Quantity_Ordered'] < 3) &
   (df['Discount_Percent'] >= 0.10)
   ].sort_values(by=['Customer_Rating'], ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
80,ORD1080,2024-03-21,Gaming,Smart Thermostat,1,269.01,Sydney,Credit Card,5.0,False,0.15,Completed,WH-1,269.01
271,ORD1271,2024-09-28,Audio,RGB Mechanical Keyboard,2,228.20,Sydney,Credit Card,5.0,True,0.10,No Return,WH-1,456.40
261,ORD1261,2024-09-18,Smart Home,Smart Eco Hub,1,26.12,London,Debit Card,5.0,True,0.10,Completed,WH-5,26.12
203,ORD1203,2024-07-22,Audio,RGB Mechanical Keyboard,1,314.52,London,Crypto,5.0,False,0.10,No Return,WH-2,314.52
453,ORD1453,2025-03-29,Gaming,Smart Eco Hub,2,288.97,Mumbai,PayPal,5.0,True,0.15,No Return,WH-3,577.94

### Que-7 Filter for orders processed by "WH-1" or "WH-2" that did not use express shipping. Sort by Ordrr_Date descending.

In [49]:
df[(df['Warehouse_Code'].isin(['WH-1', 'WH-2'])) &
   (df['Is_Express_Shipping'] == False)
   ].sort_values(by='Order_Date', ascending = True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
10,ORD1010,2024-01-11,Accessories,USB-C MegaDock,10,257.80,Sydney,PayPal,2.0,False,0.00,No Return,WH-2,2578.00
17,ORD1017,2024-01-18,Gaming,USB-C MegaDock,5,311.80,London,Credit Card,5.0,False,0.05,No Return,WH-1,1559.00
22,ORD1022,2024-01-23,Accessories,Smart Eco Hub,7,22.13,London,Crypto,3.0,False,0.15,No Return,WH-2,154.91
39,ORD1039,2024-02-09,Wearables,Noise-Cancel Headphones,6,94.99,New York,Crypto,4.0,False,0.10,No Return,WH-2,569.94
46,ORD1046,2024-02-16,Wearables,Noise-Cancel Headphones,8,20.99,London,Crypto,2.0,False,0.00,Completed,WH-1,167.92

### Que-6 Filter for transactions where the Quantity_ordered is an ordered is an odd number (1,3,5,7,9). Sort by Quantity_ordered and then by Customer_Rating descending.

In [50]:
df[(df['Quantity_Ordered'].isin([1,3,5,7,9]))
   ].sort_values(['Quantity_Ordered','Customer_Rating'], ascending=[True, False]).head(100)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
65,ORD1065,2024-03-06,Accessories,Ultra-Wide Monitor,1,218.59,New York,Crypto,5.0,True,0.00,Pending,WH-1,218.59
77,ORD1077,2024-03-18,Accessories,Ultra-Wide Monitor,1,348.29,London,Crypto,5.0,True,0.05,No Return,WH-2,348.29
80,ORD1080,2024-03-21,Gaming,Smart Thermostat,1,269.01,Sydney,Credit Card,5.0,False,0.15,Completed,WH-1,269.01
122,ORD1122,2024-05-02,Gaming,RGB Mechanical Keyboard,1,305.54,Berlin,Credit Card,5.0,False,0.05,No Return,WH-1,305.54
146,ORD1146,2024-05-26,Accessories,Smart Eco Hub,1,102.03,London,Crypto,5.0,False,0.00,No Return,WH-1,102.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,ORD1198,2024-07-17,Gaming,Wireless Buds Pro,3,228.91,Tokyo,Credit Card,2.0,False,0.00,No Return,WH-1,686.73
226,ORD1226,2024-08-14,Wearables,Noise-Cancel Headphones,3,56.94,Berlin,PayPal,2.0,True,0.15,No Return,WH-2,170.82
455,ORD1455,2025-03-31,Wearables,Smart Eco Hub,3,197.40,London,Crypto,2.0,False,0.00,No Return,WH-3,592.20
116,ORD1116,2024-04-26,Wearables,RGB Mechanical Keyboard,3,204.52,Sydney,Debit Card,1.0,True,0.00,No Return,WH-2,613.56
289,ORD1289,2024-10-16,Accessories,Noise-Cancel Headphones,3,191.34,New York,PayPal,1.0,True,0.15,No Return,WH-1,574.02

### Que-7 Filters for orders processed by "WH-1" or "WH-2" that did not use express shipping. Sort by Order_date ascending.

In [51]:
df[(df['Is_Express_Shipping'] == False) &
   (df['Warehouse_Code'].isin(['WH-1','WH-2']))
   ].sort_values(by='Order_Date', ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
10,ORD1010,2024-01-11,Accessories,USB-C MegaDock,10,257.80,Sydney,PayPal,2.0,False,0.00,No Return,WH-2,2578.00
17,ORD1017,2024-01-18,Gaming,USB-C MegaDock,5,311.80,London,Credit Card,5.0,False,0.05,No Return,WH-1,1559.00
22,ORD1022,2024-01-23,Accessories,Smart Eco Hub,7,22.13,London,Crypto,3.0,False,0.15,No Return,WH-2,154.91
39,ORD1039,2024-02-09,Wearables,Noise-Cancel Headphones,6,94.99,New York,Crypto,4.0,False,0.10,No Return,WH-2,569.94
46,ORD1046,2024-02-16,Wearables,Noise-Cancel Headphones,8,20.99,London,Crypto,2.0,False,0.00,Completed,WH-1,167.92

### Que-8 Find all records where the Unit_price is strictly between $75 and $150. Sort the output by product_category and then by unit_price ascending.

In [52]:
df[(df['Unit_Price'].between(75,150, inclusive='both'))
   ].sort_values(by=['Product_Category', 'Unit_Price'], ascending = [True,True]
                 ).head(10)

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
341,ORD1341,2024-12-07,Accessories,Ultra-Wide Monitor,4,75.19,London,Credit Card,3.0,False,0.00,No Return,WH-3,300.76
229,ORD1229,2024-08-17,Accessories,Ultra-Wide Monitor,10,82.18,Sydney,PayPal,4.0,True,0.10,Pending,WH-3,821.80
383,ORD1383,2025-01-18,Accessories,Wireless Buds Pro,1,83.96,New York,PayPal,3.0,False,0.05,No Return,WH-3,83.96
334,ORD1334,2024-11-30,Accessories,USB-C MegaDock,5,85.57,Mumbai,Debit Card,5.0,True,0.00,Pending,WH-3,427.85
51,ORD1051,2024-02-21,Accessories,RGB Mechanical Keyboard,10,88.12,Berlin,Credit Card,5.0,False,0.00,No Return,WH-3,881.20
69,ORD1069,2024-03-10,Accessories,Wireless Buds Pro,10,88.86,New York,PayPal,4.0,True,0.15,No Return,WH-3,888.60
305,ORD1305,2024-11-01,Accessories,Smart Eco Hub,9,91.53,Berlin,Crypto,1.0,False,0.00,No Return,WH-1,823.77
204,ORD1204,2024-07-23,Accessories,USB-C MegaDock,5,92.03,Mumbai,Crypto,4.0,False,0.10,No Return,WH-3,460.15
19,ORD1019,2024-01-20,Accessories,Noise-Cancel Headphones,5,93.04,New York,PayPal,3.0,False,0.00,No Return,WH-5,465.20
293,ORD1293,2024-10-20,Accessories,Ultra-Wide Monitor,7,97.78,London,Debit Card,2.0,False,0.00,No Return,WH-3,684.46

### Que-9 Extract rows from "Sydney" where the payment method was "Crypto" and the rating below 4.0. Sort by Order_ID.

In [53]:
df[(df['Store_Location'].isin(['Sydney'])) &
   (df['Payment_Method'].isin(['Crypto'])) &
   (df['Customer_Rating'] < 4.0)
   ].sort_values(by=['Order_ID'], ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
172,ORD1172,2024-06-21,Wearables,Smart Thermostat,5,58.58,Sydney,Crypto,3.0,True,0.00,No Return,WH-1,292.90
188,ORD1188,2024-07-07,Audio,FitBand X,4,88.96,Sydney,Crypto,3.0,True,0.05,No Return,WH-2,355.84
191,ORD1191,2024-07-10,Gaming,RGB Mechanical Keyboard,5,234.26,Sydney,Crypto,3.0,True,0.15,No Return,WH-4,1171.30
285,ORD1285,2024-10-12,Gaming,FitBand X,7,198.44,Sydney,Crypto,2.0,False,0.00,No Return,WH-2,1389.08
342,ORD1342,2024-12-08,Smart Home,Noise-Cancel Headphones,5,94.58,Sydney,Crypto,3.0,False,0.00,Completed,WH-5,472.90

### Que-10 Filter for orders conataining either "Smart Thermostat" or "FitBand X". Sort the final dataset by Store_Location (A-Z) and Quantity_ordered (High-Low).

In [54]:
df[(df['Product_Name'].isin(['Smart Thermostat', 'FitBand X']))
   ].sort_values(by=['Store_Location', 'Quantity_Ordered'
                     ], ascending = [True,False]).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue
181,ORD1181,2024-06-30,Smart Home,FitBand X,10,106.66,Berlin,Credit Card,3.0,False,0.00,No Return,WH-1,1066.60
361,ORD1361,2024-12-27,Accessories,FitBand X,9,339.89,Berlin,Crypto,4.0,False,0.00,No Return,WH-4,3059.01
2,ORD1002,2024-01-03,Smart Home,Smart Thermostat,8,292.69,Berlin,Debit Card,2.0,False,0.05,No Return,WH-4,2341.52
115,ORD1115,2024-04-25,Gaming,Smart Thermostat,8,242.14,Berlin,PayPal,3.0,False,0.00,No Return,WH-2,1937.12
427,ORD1427,2025-03-03,Gaming,Smart Thermostat,8,25.18,Berlin,Crypto,5.0,True,0.00,No Return,WH-3,201.44

### Que-11 Filter for items whose final price discount (unit_price x (1- Discount_percent)) is under $100, even if the original unit price was over $100. Sort by final price descending.

In [55]:
df['Final_price'] = df['Unit_Price'] * (1 - df['Discount_Percent'])

df[(df['Final_price'] < 100) & (df['Unit_Price'] > 100)
   ].sort_values(by=['Final_price'], ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue,Final_price
233,ORD1233,2024-08-21,Accessories,Noise-Cancel Headphones,2,105.11,London,Crypto,2.0,False,0.05,Completed,WH-4,210.22,99.8545
313,ORD1313,2024-11-09,Audio,RGB Mechanical Keyboard,8,101.32,Sydney,PayPal,1.0,False,0.05,No Return,WH-2,810.56,96.2540
385,ORD1385,2025-01-20,Audio,Smart Thermostat,9,105.37,New York,PayPal,4.0,True,0.15,Completed,WH-4,948.33,89.5645
117,ORD1117,2024-04-27,Smart Home,Noise-Cancel Headphones,6,104.45,New York,PayPal,4.0,True,0.15,No Return,WH-3,626.70,88.7825
331,ORD1331,2024-11-27,Wearables,Smart Eco Hub,2,107.74,Sydney,PayPal,3.0,True,0.20,No Return,WH-4,215.48,86.1920

### Que-12 Filter for products whose names start with letters between 'A' and 'M'. Sort the results by Product_category.

In [56]:
df[(df['Product_Name'].str.upper().between('A','M'))
   ].sort_values(by=['Product_Category'], ascending=True)


# df[(df['Product_Name'].str.startswith('A')) | 
#    df['Product_Name'].str.startswith('M')
#    ].sort_values(by=['Product_Category'], ascending=True
#                  ).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue,Final_price
343,ORD1343,2024-12-09,Accessories,FitBand X,5,340.42,New York,Crypto,NaN,False,0.10,No Return,WH-5,1702.10,306.3780
42,ORD1042,2024-02-12,Accessories,FitBand X,6,111.23,London,Crypto,3.0,True,0.05,No Return,WH-3,667.38,105.6685
476,ORD1476,2025-04-21,Accessories,FitBand X,9,129.32,New York,Debit Card,4.0,False,0.00,No Return,WH-2,1163.88,129.3200
451,ORD1451,2025-03-27,Accessories,FitBand X,3,282.27,New York,Debit Card,4.0,False,0.00,No Return,WH-3,846.81,282.2700
413,ORD1413,2025-02-17,Accessories,FitBand X,5,339.92,Sydney,Crypto,2.0,False,0.00,No Return,WH-5,1699.60,339.9200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,ORD1410,2025-02-14,Wearables,FitBand X,4,251.07,New York,PayPal,5.0,True,0.00,No Return,WH-3,1004.28,251.0700
399,ORD1399,2025-02-03,Wearables,FitBand X,7,16.65,Mumbai,Crypto,4.0,True,0.00,No Return,WH-2,116.55,16.6500
59,ORD1059,2024-02-29,Wearables,FitBand X,1,220.49,Tokyo,Debit Card,2.0,False,0.00,No Return,WH-1,220.49,220.4900
449,ORD1449,2025-03-25,Wearables,FitBand X,9,285.63,New York,Crypto,3.0,True,0.00,Completed,WH-1,2570.67,285.6300
73,ORD1073,2024-03-14,Wearables,FitBand X,2,34.38,Sydney,Credit Card,3.0,False,0.00,No Return,WH-3,68.76,34.3800

### Que-13 Find the top 5% highest orders by calculated total revenue, filter out any with a "Pending" return status, and sort customer_rating descending.

In [57]:
df['Total_Revenue'] = df['Quantity_Ordered'] * df['Unit_Price']

df[(df['Total_Revenue'] > df['Quantity_Ordered'].quantile(0.5)) &
   (df['Return_Status'] == 'Pending')
   ].sort_values(by='Customer_Rating', ascending=False).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue,Final_price,Total_Revenue
26,ORD1026,2024-01-27,Smart Home,RGB Mechanical Keyboard,9,282.59,Mumbai,Crypto,5.0,False,0.0,Pending,WH-3,2543.31,282.59,2543.31
65,ORD1065,2024-03-06,Accessories,Ultra-Wide Monitor,1,218.59,New York,Crypto,5.0,True,0.0,Pending,WH-1,218.59,218.59,218.59
152,ORD1152,2024-06-01,Audio,USB-C MegaDock,2,196.32,London,PayPal,5.0,True,0.0,Pending,WH-5,392.64,196.32,392.64
334,ORD1334,2024-11-30,Accessories,USB-C MegaDock,5,85.57,Mumbai,Debit Card,5.0,True,0.0,Pending,WH-3,427.85,85.57,427.85
243,ORD1243,2024-08-31,Smart Home,Wireless Buds Pro,5,247.82,Sydney,Debit Card,5.0,True,0.0,Pending,WH-1,1239.10,247.82,1239.10

### Que-14 Filter out all ordrs that used "Debit Cards" or "Pay pal" (Leaving only alternative payments like Crypto, credit etc.). sort by Store_location and payment_method throttle.

In [58]:
# df[(df['Payment_Method'].isin(['Debit Card', 'PayPal'])) &
#    (df['Payment_Method'] != 'Crypto') &
#    (df['Payment_Method'] != 'Credit')
#    ].sort_values(by=['Store_Location', 'Payment_Method'], ascending=[True, True])

df[(df['Payment_Method'].isin(['Debit Card', 'PayPal'])) &
   (~df['Payment_Method'].isin(['Crypto', 'Credit']))
   ].sort_values(by=['Store_Location', 'Payment_Method'], ascending=[True, True])

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue,Final_price,Total_Revenue
2,ORD1002,2024-01-03,Smart Home,Smart Thermostat,8,292.69,Berlin,Debit Card,2.0,False,0.05,No Return,WH-4,2341.52,278.0555,2341.52
23,ORD1023,2024-01-24,Audio,FitBand X,4,308.03,Berlin,Debit Card,1.0,False,0.15,No Return,WH-3,1232.12,261.8255,1232.12
38,ORD1038,2024-02-08,Audio,Wireless Buds Pro,6,262.09,Berlin,Debit Card,4.0,False,0.15,No Return,WH-4,1572.54,222.7765,1572.54
67,ORD1067,2024-03-08,Wearables,Smart Thermostat,2,92.27,Berlin,Debit Card,5.0,True,0.00,No Return,WH-4,184.54,92.2700,184.54
99,ORD1099,2024-04-09,Audio,Noise-Cancel Headphones,9,44.14,Berlin,Debit Card,5.0,True,0.10,No Return,WH-3,397.26,39.7260,397.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,ORD1296,2024-10-23,Gaming,Smart Eco Hub,8,88.44,Tokyo,PayPal,5.0,False,0.10,No Return,WH-2,707.52,79.5960,707.52
335,ORD1335,2024-12-01,Wearables,Wireless Buds Pro,4,223.69,Tokyo,PayPal,5.0,False,0.20,No Return,WH-3,894.76,178.9520,894.76
396,ORD1396,2025-01-31,Gaming,RGB Mechanical Keyboard,2,64.69,Tokyo,PayPal,3.0,False,0.15,No Return,WH-1,129.38,54.9865,129.38
426,ORD1426,2025-03-02,Audio,Noise-Cancel Headphones,5,206.15,Tokyo,PayPal,5.0,True,0.00,No Return,WH-1,1030.75,206.1500,1030.75
488,ORD1488,2025-05-03,Accessories,USB-C MegaDock,6,17.53,Tokyo,PayPal,3.0,False,0.00,Completed,WH-1,105.18,17.5300,105.18

### Que-15 Filter out any rows that have any missing data in the customer_rating or "Return_status" columns. Sort the remaining clean rows by order_id sequentially.

In [59]:
# df[(df['Customer_Rating'].isna()) &
#     (df['Return_Status'].isna())
#    ].sort_values(by='Order_ID', ascending=True).head()

df[(df['Customer_Rating'].isna()) |
    (df['Return_Status'].isna())
   ].sort_values(by='Order_ID', ascending=True).head()

,Order_ID,Order_Date,Product_Category,Product_Name,Quantity_Ordered,Unit_Price,Store_Location,Payment_Method,Customer_Rating,Is_Express_Shipping,Discount_Percent,Return_Status,Warehouse_Code,Revenue,Final_price,Total_Revenue
1,ORD1001,2024-01-02,Gaming,USB-C MegaDock,8,121.90,Sydney,PayPal,NaN,True,0.05,No Return,WH-5,975.20,115.8050,975.20
14,ORD1014,2024-01-15,Accessories,USB-C MegaDock,5,279.89,Mumbai,PayPal,NaN,False,0.00,No Return,WH-4,1399.45,279.8900,1399.45
16,ORD1016,2024-01-17,Accessories,Noise-Cancel Headphones,1,224.67,Berlin,Credit Card,NaN,True,0.10,No Return,WH-4,224.67,202.2030,224.67
57,ORD1057,2024-02-27,Wearables,Wireless Buds Pro,4,331.49,New York,Debit Card,NaN,True,0.00,No Return,WH-1,1325.96,331.4900,1325.96
92,ORD1092,2024-04-02,Smart Home,Ultra-Wide Monitor,2,58.39,Sydney,Credit Card,NaN,False,0.05,No Return,WH-4,116.78,55.4705,116.78